
const $=id=>document.getElementById(id);let currentFrame=0;let autoTimer=null;let routeData=null;
function fmt(s){s=Number(s||0);if(s<60)return `${Math.round(s)}s`;return `${Math.floor(s/60)}m ${Math.round(s%60)}s`}
function msg(text,ok=false){$('form-message').textContent=text;$('form-message').style.color=ok?'#19d38a':'#ff9bd1'}
async function api(url,opts={}){const r=await fetch(url,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})},cache:'no-store'});const d=await r.json();if(!r.ok||d.status==='error')throw new Error(d.message||'Request failed');return d}
async function refreshTraffic(){try{const d=await api(`/api/traffic?frame=${currentFrame}`);$('db-status').textContent='LIVE';renderTraffic(d)}catch(e){$('db-status').textContent='ERROR';console.error(e)}}
function renderTraffic(d){currentFrame=Number(d.frame_index||0);$('traffic-grid').innerHTML=[1,2,3,4].map(j=>{const v=d.junctions[j]||d.junctions[String(j)];return `<div class="traffic-card"><h4>J${j}</h4><div class="metric-line"><span>DB record</span><b>#${v.source_id}</b></div><div class="metric-line"><span>Vehicles</span><b>${v.vehicle_count}</b></div><div class="metric-line"><span>Speed</span><b>${Number(v.average_speed).toFixed(1)} km/h</b></div><div class="metric-line"><span>Occupancy</span><b>${Number(v.lane_occupancy).toFixed(1)}%</b></div><div class="metric-line"><span>Waiting</span><b>${Number(v.waiting_time).toFixed(1)}s</b></div><div class="metric-line"><span>Congestion</span><b>${Number(v.congestion).toFixed(1)}%</b></div></div>`}).join('')}
async function plan(){try{const d=await api('/api/plan',{method:'POST',body:JSON.stringify({current_junction:Number($('current-junction').value),destination:Number($('destination').value),frame:currentFrame})});routeData=d;$('route-empty').classList.add('hidden');$('route-result').classList.remove('hidden');$('route-text').textContent=d.route.map(x=>`J${x}`).join(' → ');$('route-time').textContent=fmt(d.estimated_time_seconds);$('route-frame').textContent=`${d.frame_index+1}`;$('route-segments').innerHTML=d.segments.map(s=>`<div class="segment"><strong>J${s.from} → J${s.to}</strong><span>${s.direction} • ${Number(s.congestion_at_destination).toFixed(0)}% congestion</span><b>${fmt(s.seconds)}</b></div>`).join('');msg('A* route calculated from the current database frame.',true)}catch(e){msg(e.message)}}
async function activate(){try{const d=await api('/api/activate',{method:'POST',body:JSON.stringify({ambulance_id:$('ambulance-id').value,current_junction:Number($('current-junction').value),destination:Number($('destination').value),emergency_level:$('level').value,frame:currentFrame})});routeData=d;msg('Emergency corridor activated and written to MySQL.',true);$('trip-badge').textContent='ACTIVE';$('trip-badge').style.borderColor='#ff3ea5';await refreshStatus()}catch(e){msg(e.message)}}
async function refreshStatus(){try{const d=await api(`/api/status?frame=${currentFrame}`);renderTrip(d.emergency)}catch(e){console.error(e)}}
function renderTrip(e){if(!e?.active){$('trip-empty').classList.remove('hidden');$('trip-active').classList.add('hidden');$('trip-badge').textContent='READY';return}$('trip-empty').classList.add('hidden');$('trip-active').classList.remove('hidden');$('trip-ambulance').textContent=e.ambulance_id;$('trip-current').textContent=`J${e.current_junction}`;$('trip-next').textContent=e.next_junction?`J${e.next_junction}`:'DEST';$('trip-destination').textContent=`J${e.destination}`;$('trip-eta').textContent=fmt(e.estimated_time_seconds);$('trip-status').textContent=e.status;$('trip-progress-text').textContent=Math.round(Number(e.segment_progress||0)*100)+'%';const pct=((Number(e.route_index||0)+Number(e.segment_progress||0))/Math.max(1,e.route.length-1))*100;$('trip-progress-fill').style.width=`${Math.min(100,pct)}%`;$('trip-timeline').innerHTML=e.route.map((j,i)=>`${i>0?'<div class="tl-line"></div>':''}<div class="tl-node ${i<e.route_index?'done':''} ${i===e.route_index?'active':''}"><div class="tl-circle">J${j}</div></div>`).join('')}
async function advance(){try{const d=await api('/api/advance',{method:'POST',body:JSON.stringify({frame:currentFrame})});renderTrip(d.emergency);if(d.emergency.status==='AT DESTINATION')stopAuto()}catch(e){msg(e.message)}}
function stopAuto(){if(autoTimer){clearInterval(autoTimer);autoTimer=null}$('auto-btn').innerHTML='<i class="fa-solid fa-play"></i> Auto Dispatch'}
function startAuto(){stopAuto();$('auto-btn').innerHTML='<i class="fa-solid fa-pause"></i> Pause Auto';autoTimer=setInterval(async()=>{try{const d=await api(`/api/status?frame=${currentFrame}`);if(!d.emergency?.active){stopAuto();return}const p=Number(d.emergency.segment_progress||0);if(p>=.985)await advance();else refreshStatus()}catch(e){console.error(e)}},1000)}
$('plan-btn').onclick=plan;$('activate-btn').onclick=activate;$('advance-btn').onclick=advance;$('auto-btn').onclick=()=>autoTimer?stopAuto():startAuto();$('clear-btn').onclick=async()=>{try{await api('/api/clear',{method:'POST'});stopAuto();await refreshStatus();msg('Emergency cleared.',true)}catch(e){msg(e.message)}};setInterval(()=>{currentFrame++;refreshTraffic();refreshStatus()},2500);refreshTraffic();refreshStatus();
